### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by sam1991a** [IS4Code/PawnPlus#58]
I'm doing a samp server, and I put the PawnPlus include on my server, my host is linux, I uploaded PawnPlus.so, but this warning appears, I have no idea what it is. Also after a few minutes the server simply doesn't load the files, it's still online, but as if it were a "Blank Script"

[PawnPlus] Warning: amx_FindPublic returned negative index -10072 for function 'pp_on_error'. Possible collision with SAMPGDK detected. Use pp_public_min_index or pp_use_funcidx to remove this warning.
[PawnPlus] pool_add_arr: pool reference is invalid (value 0x0)

**Comment by IS4Code** [comment]
Hello, the two messages are unrelated.

The first one is caused by SAMPGDK-based plugins which claim that `pp_on_error` is an existing function in your code even though it isn't. It's not necessarily an issue, but some routines in PawnPlus may decide differently based on its presence. See the [wiki](//github.com/IS4Code/PawnPlus/wiki/Known-incompatibilities) for more details here.

"pool reference is invalid" just means that you used `pool_add_arr` on an uninitialized pool instance, i.e. you forgot `pool_new` somewhere.
